sudo: false
language: node_js
cache:
  npm
notifications:
  email: false
services: postgresql
node_js:
  - 10.19.0
before_install:
  - npm i -g npm@^6.13.4
before_script:
  - sudo -u postgres psql -c 'create database polycade;' 
  - sudo -u postgres psql  -d polycade < polycade.dmp
  - npm prune
script:
  - npm t
env:
  global:
    PGHOST=localhost
    PGDATABASE=polycade
    PGPORT=5432
    PGUSER=postgres    

