branches:
  only:
  - master
  - travis-ci
language: node_js
dist: xenial
os: linux
cache: npm
notifications:
  email: false
addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11
node_js:
  - 10.19.0
before_install:
  - npm i -g npm@^6.13.4
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/11/main/postgresql.conf
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo systemctl restart postgresql@11-main
  - psql -U postgres -c "CREATE DATABASE travis_ci_test"
  - psql -U postgres -d travis_ci_test < ./db/polycade.dmp  
before_script:
  - npm prune
script:
  - npm t
env:
  global:
    - DB_HOST=localhost
    - DB_NAME=travis_ci_test
