sudo: false
language: node_js
cache:
  npm
notifications:
  email: false
services: postgresql
node_js:
  - 10.19.0
before_install:
  - npm i -g npm@^6.13.4
before_script:
  - psql -U postgres -c 'create database travis_ci_test;'
  - psql -U postgres -d travis_ci_test < polycade.dmp
  - npm prune
script:
  - npm t
env:
  global:
    - PGHOST=localhost
    - PGDATABASE=travis_ci_test
    - PGPORT=5432
    - PGUSER=postgres    

