sudo: false
language: node_js
cache:
  npm
notifications:
  email: false
services: postgresql
node_js:
  - 10.19.0
before_install:
  - npm i -g npm@^6.13.4
before_script:
  - psql -c 'create database polycade;' -U postgres
  - psql -U postgres -d polycade < polycade.dmp
  - npm prune
script:
  - npm t
env:
  global:
    PGDATABASE=polycade

