codecov:
  require_ci_to_pass: yes
  token: "7d0adfe7-7b5c-4786-8841-3ea42dc539b4"

coverage:
  precision: 2
  round: down
  range: "70...100"

parsers:
  javascript:
    enable_partials: yes
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
