# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Postgres 11 Setup
      uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '11'
        postgresql db: 'polycade_test'
    - name: Import Seed db
      uses: n1ru4l/psql-action@v1
      with:
        POSTGRES_PASSWORD: ''
        POSTGRES_DATABASE: 'polycade_test'
        DATABASE_DUMP_PATH: './db/polycade.dmp'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
