# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master, cipatch ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: polycade_test
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        
    steps:
    - uses: actions/checkout@v2
    - name: Db Migration
      run: |
        sudo chmod 777 ./db/polycade.dmp
        which psql
        psql -U postgres -d polycade_test < ./db/polycade.dmp
      env:
        PGHOST: localhost
        PGUSER: postgres
        PGPORT: 5432
        PGPASSWORD: postgres
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}   
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
        DB_NAME: polycade_test
        DB_PASS: postgres
