# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Postgres 11 Setup
      uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '11'
        postgresql db: 'polycade_test'
    - run: sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/11/main/postgresql.conf
    - run: sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
    - run: sudo systemctl restart postgresql@11-main
    - run: psql -U postgres -d 'polycade_test' < './db/polycade.dmp'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
        DB_NAME: 'polycade_test' 
